# Numpy in 1D
Library for scientific computing. Basis for pandas.


**How to create a Numpy Array?**

Numpy array or ndarray, similar to a list, fixed, todos los elementos del mismo tipo.

Cast a list to an array:

```
  #lista a
a = [0, 1, 2, 3, 4]
  #array b
b = np.array(a)
```

---

**Attributes**

* b.size --- number of elements
* b.ndim --- numnber of array dimensions OR the rank of the array ¿cuántas dimensiones?
* b.shape --- tupla que indica el tamaño de cada una de las dimensiones


---

**Indexing and Slicing methods**

* reglas básicas de un array
* son mutables
* como listas y tuplas, se pueden cortar

```
arrayA = np.array([20, 1, 2, 3, 4])
arrayB = arrayA[1:4]
  #esto imprime 1, 2, 3

  #o podemos cambiar valores
arrayA[3:5] = 300, 400
  #que sería [20, 1, 2, 300, 400]
```

---

**Basic Operations**

Suma de vectores:
```
u = [1, 0]
v = [1, 0]
z = []

for n, m in zip(u, v)
  z.append(n + m)
```


O usando numpy se puede hacer en una sola linea, sin ciclos:
```
u = np.array([1, 0])
v = np.array([0, 1])

z = u + v
#o z = u - v
```


Multiplicación escalar es un vector por un número.
```
y = np.array([1, 2])

z = 2*y
#[2, 4]
```


Multiplicación de dos vectores
```
u = np.array([1, 2])
v = np.array([3, 2])

z = u*v
#[3, 4]
```


Dot product
```
u = np.array([1, 2])
v = np.array([3, 1])

result = np.dot(u, v)
#5
```


Broadcasting
```
u = np.array([1, 2, 3, -1])
z = u+1

#[2, 3, 4, 0]
```


---

**Universal Functions**

* b.mean --- promedio
* b.max --- máximo valor
* np.pi --- número pi
* x = np.array([0, np.pi/2, np.pi]) --- coloca en radianes: [0, pi/2, pi]
* y = np.sin(x) --- esto le aplicaría el seno a cada uno de los valores en x, o sea: [0, 1, 1.2e-16]



---

**For plotting**

```
np.linespace(-2, 2, num=5)
#-2, -1, 0, 1, 2


np.linespace(-2, 2, num=9)
#-2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2
```

Y recuerda que con **import matplotlib.pyplot as plt**, podemos usar el comando:

%maplotlib inline
plt.plt(x, y)



---

# Lab - Working with 1D Numpy Arrays

*Try it yourself* exercises

In [ ]:
#Assign the value 20 for the second element in the given array.
import numpy as np 

a = np.array([10, 2, 30, 40,50])

a[1] = 20
a

array([10, 20, 30, 40, 50])

In [ ]:
#Print the even elements in the given array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[1:8:2]

array([2, 4, 6, 8])

In [ ]:
#Find the size ,dimension and shape for the given array b
b = np.array([10, 20, 30, 40, 50, 60, 70])

b.size
b.ndim
b.shape

(7,)

In [ ]:
#Find the sum of maximum and minimum value in the given numpy array
c = np.array([-10, 201, 43, 94, 502])

c.max() + c.min()

492

In [ ]:
#Perform addition operation on the given numpy array arr1 and arr2:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

np.add(arr1, arr2)


#Perform subtraction operation on the given numpy array arr1 and arr2:
arr3 = np.array([10, 20, 30, 40, 50, 60])
arr4 = np.array([20, 21, 22, 23, 24, 25])

np.subtract(arr3, arr4)

array([-10,  -1,   8,  17,  26,  35])

In [ ]:
#Perform multiply operation on the given numpy array arr1 and arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

arr3 = arr1 * arr2
#o también np.multiply(arr1, arr2)
#o para divisiones: np.divide(arr1, arr2)
arr3

array([ 20,  20,  60, 120, 200, 300])

In [ ]:
#Make a numpy array within [5, 4] and 6 elements
np.linespace(5, 4, num=6)

---

# Numpy in 2D

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

A = np.array(a)

```
   11  12  13
A: 21  22  23
   31  32  33
```

* A.ndim -> sería de 2 dimensiones
* A.shape -> sería (3, 3)
  * 3 filas y 3 columnas
* A.size -> 9



---


* Se pueden sumar matrices como una suma
* Se puede multiplicar una matriz por un valor escalar, como un vector
* Se pueden multiplicar las matrices de manera natural (cuadro por cuadro --- dot product)
  * A x B
* O se puede hace la multiplicación EXTRAVAGANTE
  * np.dot(A,B)



# Lab - Working with 2D Numpy Arrays

*Quiz on 2D Numpy Array* exercises

In [2]:
#Consider the following list a, convert it to Numpy Array.
import numpy as np 
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

b = np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
#Calculate the numpy array size.
b.size

12

In [5]:
#Access the element on the first row and first and second columns.
b[0][0:2]

array([1, 2])

In [6]:
#Perform matrix multiplication with the numpy arrays A and B.
A = b
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

---

# Simple APIs
# Labs APIs
Aplication Program Interfaces

* Like a Big Function
* REST = REpresentational State Transfer
* REST for web services
  * HTTP Request with a JSON



nba_api by Swar Patel


```
!pip install nba_api
from nba_api.stats.static import teams
nba_teams = teams.get_teams()
nba_teams[:5]

#esto devuelve info de los equipos de la nba en forma de un diccionario
```

Cada vez que usamos nba_api estamos haciendo peticiones a la página.

* Para usar un API siempre necesitamos el endpoint (url) y las llaves de acceso que nos identifican como user (key)

In [9]:
import requests

import os 
from PIL import Image
from IPython.display import IFrame

url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt'
path=os.path.join(os.getcwd(),'example1.txt')
r=requests.get(url)
with open(path,'wb') as f:
    f.write(r.content)

In [10]:
#Exercise 1
#In this Exercise, generate photos of the random 5 users.
!pip install randomuser
from randomuser import RandomUser
import pandas as pd

r = RandomUser()

some_list = r.generate_users(5)

for user in some_list:
    print (user.get_picture())

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5084 sha256=a69ad27f5b66e0e7da23daf686991e41f2bf79f64df6a516dcffe1b7fd1bd4e8
  Stored in directory: /root/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/89.jpg
https://randomuser.me/api/portraits/men/51.jpg
https://randomuser.me/api/portraits/women/28.jpg
https://randomuser.me/api/portraits/women/13.jpg


In [11]:
#Exercise 2
#In this Exercise, find out how many calories are contained in a banana.

import requests
import json

#We will obtain the fruitvice API data using requests.get("url")
data = requests.get("https://www.fruityvice.com/api/fruit/all")

#We will retrieve results using json.loads() function
results = json.loads(data.text)

#We will convert our json data into pandas data frame.
pd.DataFrame(results)

#The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.
df2 = pd.json_normalize(results)

cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96